### ISSUE TITLE
folder sizing looks bad when there is only one app inside the folder

### ISSUE THREAD

**Issue by aghnu** [Selenium-H/App-Grid-Tweaks#10]
![Screenshot from 2021-10-02 04-32-31](https://user-images.githubusercontent.com/46549455/135712652-f59bb813-0f9f-4487-8534-2277c0dd1c84.png)

folder rows: 2
folder columns: 4
app grid rows: 3
app grid columns: 6
app icon size: 62
app icon label font size: 13
application label style: normal

**Comment by Selenium-H** [comment]
Fixed with last commit in [experimental](https://github.com/Selenium-H/App-Grid-Tweaks/tree/experimental) `branch`.
