### ISSUE TITLE
Not compatible GNOME 41

### ISSUE THREAD

**Issue by heinthanth** [Selenium-H/App-Grid-Tweaks#12]
Fedora 35 is released and I just installed it. How to make this extension working on GNOME 41.

I've tried cloning this repo and running `INSTALL.sh` but can't enable in `gnome-extensions-app`.

**Comment by heinthanth** [comment]
But I changed `metadata.json` ( add "41" ) and it works now :P

**Comment by jmauss** [comment]
Also looking forward to official Gnome 41 support

**Comment by heinthanth** [comment]
Developer himself or someone with write access should publish those changes. Should I create pull request ( but it's not necessary since just "41" is need to be added to version array )?

**Comment by heinthanth** [comment]
Since the PR is merged, I closed this issue! Thanks for PR!

**Comment by jmauss** [comment]
Note: doesn't look like the extensions.gnome.org page has been updated yet.
