### ISSUE TITLE
Folder view changes only after logout

### ISSUE THREAD

**Issue by fawtytoo** [Selenium-H/App-Grid-Tweaks#3]
The folder view doesn't seem to update after clicking the refresh button. Works fine for Apps.

**Comment by Selenium-H** [comment]
Thanks @fawtytoo for `Application View Columns Extension`.
Just to confirm, do you have app grid spring animations turned off ?

**Comment by fawtytoo** [comment]
Interestingly, yes. And also Hide Dash Forked appears to affect it. Disabling both of those fixes it.

**Comment by Selenium-H** [comment]
Thanks for confirming. Actually, the app folder views are updated after spring animation is over. I'll update once a proper alternative is found.

**Comment by fawtytoo** [comment]
Just to add, some of my own extensions also interfere, namely Show Applications instead of Workspaces.

**Comment by Selenium-H** [comment]
Last commit in [main](https://github.com/Selenium-H/App-Grid-Tweaks/tree/main) branch fixed this issue.
