### ISSUE TITLE
)

### ISSUE THREAD

**Issue by ashikashihere** [Selenium-H/App-Grid-Tweaks#4]
.

**Comment by Selenium-H** [comment]
The extension currently works with GNOME Shell version 3.38 only. Could you please state the GNOME Shell version you're using?

**Comment by ashikashihere** [comment]
Oh okay. Im using pop-os 20.4 lts,so i think im not using the gnome v3.38.
thank you

**Comment by ashikashihere** [comment]
Sorry im using 3.36
