### ISSUE TITLE
Small icons within folders

### ISSUE THREAD

**Issue by goznalo-git** [Selenium-H/App-Grid-Tweaks#7]
Hi there, 

I am a Manjaro Linux users, and a couple of weeks ago, I guess that in preparation for Gnome 40's app grid layout, they increased the default number of columns, which clashed with my left "favorite apps" dock. I have thus tried using App Grid Tweaks, adjusting the number of columns.

It works fine, except for the fact that sometimes when opening a folder, it displays very small icons and corresponding text. To trigger this manually, I can pull an icon outside its folder, and it always happens. Here is [a screenshot](https://imgur.com/a/4w8NY4s).

To give you an idea of my relevant specs:
```bash
$ cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.4
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

```bash
$ gnome-shell --version
GNOME Shell 3.38.4
```

Please let me know if I can provide you further information.

Thanks,
G.

**Comment by Selenium-H** [comment]
Sorry for the delay. Last commit in [Experimental](https://github.com/Selenium-H/App-Grid-Tweaks/tree/Experimental) `branch` fixed this issue.
